package edu.sjfc.seleniumTest;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Arrays;
import java.util.Collection;


public class TeddisjfceduTest {
	
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  String domain = "https://teddi.sjfc.edu/";
  
  @Before
  public void setUp() {
    // driver = new ChromeDriver();
	  
	File file = new File("p:\\Selenium\\msedgedriver.exe");
	System.setProperty("webdriver.edge.driver", file.getAbsolutePath());
	  
	driver = new org.openqa.selenium.edge.EdgeDriver();
	driver.manage().window().setSize(new Dimension(1024,768));
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  
  @After
  public void tearDown() {
    driver.quit();
  }
  
  @Test
  public void teddiTest2356() {
    driver.get(domain.concat("teddi40-dedication/"));
    driver.findElement(By.cssSelector(".copyright"));
  }

  @Test
  public void teddiTest2250() {
    driver.get(domain.concat("schedule-tester/"));
    driver.findElement(By.cssSelector(".copyright"));
  }

  @Test
  public void teddiTest2231() {
    driver.get(domain.concat("teddi39-dedication/"));
    driver.findElement(By.cssSelector(".copyright"));
  }

  @Test
  public void teddiTest2212() {
    driver.get(domain.concat("how-you-can-help/"));
    driver.findElement(By.cssSelector(".copyright"));
  }

  @Test
  public void teddiTest2194() {
    driver.get(domain.concat("sponsors/"));
    driver.findElement(By.cssSelector(".copyright"));
  }

  @Test
  public void teddiTest2135() {
    driver.get(domain.concat("teddi38-dedication/"));
    driver.findElement(By.cssSelector(".copyright"));
  }

  @Test
  public void teddiTest2081() {
    driver.get(domain.concat("teddi-turkey-bowl-flag-football-game/"));
    driver.findElement(By.cssSelector(".copyright"));
  }

  @Test
  public void teddiTest1919() {
    driver.get(domain.concat("teddi-knockout-basketball/"));
    driver.findElement(By.cssSelector(".copyright"));
  }

  @Test
  public void teddiTest1819() {
    driver.get(domain.concat("404-2/"));
    driver.findElement(By.cssSelector(".copyright"));
  }

  @Test
  public void teddiTest1743() {
    driver.get(domain.concat("teddi37-dedication/"));
    driver.findElement(By.cssSelector(".copyright"));
  }

  @Test
  public void teddiTest1719() {
    driver.get(domain.concat("teddi-volleyball-registration/"));
    driver.findElement(By.cssSelector(".copyright"));
  }

  @Test
  public void teddiTest1667() {
    driver.get(domain.concat("teddi-trick-shot-registration/"));
    driver.findElement(By.cssSelector(".copyright"));
  }

  @Test
  public void teddiTest1607() {
    driver.get(domain.concat("teddi-kickball-registration/"));
    driver.findElement(By.cssSelector(".copyright"));
  }

  @Test
  public void teddiTest1564() {
    driver.get(domain.concat("teddi36-dedicaton-kenny-bremer/"));
    driver.findElement(By.cssSelector(".copyright"));
  }

  @Test
  public void teddiTest1462() {
    driver.get(domain.concat("registration-reports/"));
    driver.findElement(By.cssSelector(".copyright"));
  }

  @Test
  public void teddiTest1427() {
    driver.get(domain.concat("teddi35-dedication-courtney-wagner/"));
    driver.findElement(By.cssSelector(".copyright"));
  }

  @Test
  public void teddiTest1395() {
    driver.get(domain.concat("quick-reg/quick-reg-dancer-outside-fisher/"));
    driver.findElement(By.cssSelector(".copyright"));
  }

  @Test
  public void teddiTest1393() {
    driver.get(domain.concat("quick-reg/quick-reg-volunteer-fisher-id/"));
    driver.findElement(By.cssSelector(".copyright"));
  }

  @Test
  public void teddiTest1394() {
    driver.get(domain.concat("quick-reg/quick-reg-volunteer-outside-fisher/"));
    driver.findElement(By.cssSelector(".copyright"));
  }

  @Test
  public void teddiTest1390() {
    driver.get(domain.concat("quick-reg/"));
    driver.findElement(By.cssSelector(".copyright"));
  }

  @Test
  public void teddiTest1319() {
    driver.get(domain.concat("teddi-trot/teddi-trot-registrants/"));
    driver.findElement(By.cssSelector(".copyright"));
  }

  @Test
  public void teddiTest1313() {
    driver.get(domain.concat("teddi-trot/teddi-trot-5k-and-fun-run-registration-outside-fisher/"));
    driver.findElement(By.cssSelector(".copyright"));
  }

  @Test
  public void teddiTest1310() {
    driver.get(domain.concat("teddi-trot/teddi-trot-5k-and-fun-run-registration/"));
    driver.findElement(By.cssSelector(".copyright"));
  }

  @Test
  public void teddiTest1277() {
    driver.get(domain.concat("register/dance-registration-outside-fisher/"));
    driver.findElement(By.cssSelector(".copyright"));
  }

  @Test
  public void teddiTest1283() {
    driver.get(domain.concat("start-registration/"));
    driver.findElement(By.cssSelector(".copyright"));
  }

  @Test
  public void teddiTest1281() {
    driver.get(domain.concat("register/volunteer-registration-outside-fisher/"));
    driver.findElement(By.cssSelector(".copyright"));
  }

  @Test
  public void teddiTest1274() {
    driver.get(domain.concat("register/dance-registration-fisher-id/"));
    driver.findElement(By.cssSelector(".copyright"));
  }

  @Test
  public void teddiTest1262() {
    driver.get(domain.concat("keeping-up-with-the-committee/"));
    driver.findElement(By.cssSelector(".copyright"));
  }

  @Test
  public void teddiTest1234() {
    driver.get(domain.concat("teddi-dance-hourly-schedule-public/"));
    driver.findElement(By.cssSelector(".copyright"));
  }

  @Test
  public void teddiTest1228() {
    driver.get(domain.concat("teddi34-dedicated-to-amanda-conrow/"));
    driver.findElement(By.cssSelector(".copyright"));
  }

  @Test
  public void teddiTest1207() {
    driver.get(domain.concat("enter-hourly-events/"));
    driver.findElement(By.cssSelector(".copyright"));
  }

  @Test
  public void teddiTest1178() {
    driver.get(domain.concat("quick-reg/dancer-fisherid/"));
    driver.findElement(By.cssSelector(".copyright"));
  }

  @Test
  public void teddiTest1060() {
    driver.get(domain.concat("teddi33-dedication-ashley-nagel/"));
    driver.findElement(By.cssSelector(".copyright"));
  }

  @Test
  public void teddiTest1044() {
    driver.get(domain.concat("teddi-dance-hourly-schedule/"));
    driver.findElement(By.cssSelector(".copyright"));
  }

  @Test
  public void teddiTest1032() {
    driver.get(domain.concat("teddi-is-live/"));
    driver.findElement(By.cssSelector(".copyright"));
  }

  @Test
  public void teddiTest838() {
    driver.get(domain.concat("teddi-trot/"));
    driver.findElement(By.cssSelector(".copyright"));
  }

  @Test
  public void teddiTest790() {
    driver.get(domain.concat("calendar/"));
    driver.findElement(By.cssSelector(".copyright"));
  }

  @Test
  public void teddiTest774() {
    driver.get(domain.concat("teddi32-dedication/"));
    driver.findElement(By.cssSelector(".copyright"));
  }

  @Test
  public void teddiTest728() {
    driver.get(domain.concat("teddi-photos/"));
    driver.findElement(By.cssSelector(".copyright"));
  }

  @Test
  public void teddiTest691() {
    driver.get(domain.concat("sponsors-2/"));
    driver.findElement(By.cssSelector(".copyright"));
  }

  @Test
  public void teddiTest671() {
    driver.get(domain.concat("teddi-live-public/"));
    driver.findElement(By.cssSelector(".copyright"));
  }

  @Test
  public void teddiTest496() {
    driver.get(domain.concat("teddi-alumni/"));
    driver.findElement(By.cssSelector(".copyright"));
  }

  @Test
  public void teddiTest489() {
    driver.get(domain.concat("?page_id=489"));
    driver.findElement(By.cssSelector(".copyright"));
  }

  @Test
  public void teddiTest392() {
    driver.get(domain.concat("live-video/"));
    driver.findElement(By.cssSelector(".copyright"));
  }

  @Test
  public void teddiTest328() {
    driver.get(domain.concat("children-with-hair-loss-for-teddi-thank-you/"));
    driver.findElement(By.cssSelector(".copyright"));
  }

  @Test
  public void teddiTest242() {
    driver.get(domain.concat("rsstest/"));
    driver.findElement(By.cssSelector(".copyright"));
  }

  @Test
  public void teddiTest218() {
    driver.get(domain.concat("tweets-archive/"));
    driver.findElement(By.cssSelector(".copyright"));
  }

  @Test
  public void teddiTest165() {
    driver.get(domain.concat("children-with-hair-loss-for-teddi/stylist-registration/"));
    driver.findElement(By.cssSelector(".copyright"));
  }

  @Test
  public void teddiTest153() {
    driver.get(domain.concat("children-with-hair-loss-for-teddi/for-stylists/"));
    driver.findElement(By.cssSelector(".copyright"));
  }

  @Test
  public void teddiTest129() {
    driver.get(domain.concat("children-with-hair-loss-for-teddi/"));
    driver.findElement(By.cssSelector(".copyright"));
  }

  @Test
  public void teddiTest113() {
    driver.get(domain.concat("about/about-teddi/"));
    driver.findElement(By.cssSelector(".copyright"));
  }

  @Test
  public void teddiTest83() {
    driver.get(domain.concat(""));
    driver.findElement(By.cssSelector(".copyright"));
  }

  @Test
  public void teddiTest72() {
    driver.get(domain.concat("forms/"));
    driver.findElement(By.cssSelector(".copyright"));
  }

  @Test
  public void teddiTest66() {
    driver.get(domain.concat("email-us/"));
    driver.findElement(By.cssSelector(".copyright"));
  }

  @Test
  public void teddiTest34() {
    driver.get(domain.concat("register/volunteer-registration-fisher-id/"));
    driver.findElement(By.cssSelector(".copyright"));
  }

  @Test
  public void teddiTest28() {
    driver.get(domain.concat("register/"));
    driver.findElement(By.cssSelector(".copyright"));
  }

  @Test
  public void teddiTest26() {
    driver.get(domain.concat("get-involved/"));
    driver.findElement(By.cssSelector(".copyright"));
  }

  @Test
  public void teddiTest24() {
    driver.get(domain.concat("event/"));
    driver.findElement(By.cssSelector(".copyright"));
  }

  @Test
  public void teddiTest19() {
    driver.get(domain.concat("about/meet-the-committee/"));
    driver.findElement(By.cssSelector(".copyright"));
  }

  @Test
  public void teddiTest9() {
    driver.get(domain.concat("about/"));
    driver.findElement(By.cssSelector(".copyright"));
  }

}
